#!/bin/sh

#ARCHS="i586 x86_64"
ARCHS="x86_64"

#if [ ! "$UID" = "0" ]; then#
#	echo "Restarting as root.."
#	exec sudo $0
#fi

# a temporary hack to make python 2.6 work
#export PYTHONPATH=/usr/lib/python2.6/site-packages/

DIRNAME=$(dirname $0)
cd $DIRNAME

build_root="/opt/"

d=`date +%Y.%m.%d-%H.%M`

product_id="Mandriva.2011.RC2"
product_name_file="${build_root}/${product_id}/.name.txt" ; touch ${product_name_file}

#ks="${build_root}/${product_id}/.ks"

ks="${build_root}/${product_id}/.ks"
counter="${build_root}/${product_id}/.counter"
menu="${build_root}/${product_id}/.menu.xml"

touch ${counter}

i=`cat ${counter}`
i=`expr $i + 1`

echo $i > ${counter}

echo "$i.$d" > ${build_root}/${product_id}/version.txt

# build different architectures

for arch in $ARCHS; do
	cp -f ${ks}.template ${ks}
	sed -i -e "s:#ARCH#:$arch:g" ${ks}
	sed -i -e "s:#PATH#:${build_root}/${product_id}:g" ${ks}
	sed -i -e "s:#PATH#:${build_root}/${product_id}:g" ${menu}

	mkdir -p $build_root/iso/${product_id}/
	livecd-creator --config=${ks} --fslabel=${product_id}.$arch.$i --menu-config=${build_root}/${product_id}/.menu.xml

	mv ${product_id}.$arch.$i.iso $build_root/iso/${product_id}/
	isohybrid $build_root/iso/${product_id}/${product_id}.$arch.$i.iso
	md5sum  $build_root/iso/${product_id}/${product_id}.$arch.$i.iso > $build_root/iso/${product_id}/${product_id}.$arch.$i.iso.md5sum

	echo ""
	echo "          ALL DONE!        $build_root/iso/${product_id}/${product_id}.$arch.$i.iso"
	echo ""
done